### PR TITLE
Angular universal-compatibility

### PR DESCRIPTION
**Pull request by ZNS**
Simple check if platform is browser before creating Splide instance

### CODE REVIEW

**Comment by wiistriker** [comment]
Hello! Thank you for PR. Could you please tell me why we need this check? I think no one will require this package in non-web apps

**Comment by ZNS** [comment]
I'm using your library in a angular universal https://angular.io/guide/universal project which renders the app on the server before loading the browser application. This check makes sure the server side script doesn't break.

**Comment by wiistriker** [comment]
Just released 0.0.16 on npm

**Comment by ZNS** [comment]
Thanks! 👍

**Pull request merged**
